
export const LocalDB: {[index: string]: any} = {

    // fighter

    fighter_hp: 10,
    fighter_hp_incPercentByLevel: 10,
    fighter_shield_min: 50,
    fighter_shield_max: 90,
    fighter_shield_incPercentByLevel: 10,
    fighter_attackPower_min: 10,
    fighter_attackPower_max: 15,
    fighter_attackPower_incPercentByLevel: 10,
    fighter_attackSpeedPersSec_min: 0.8,
    fighter_attackSpeedPersSec_max: 1,
    fighter_hitPenetrationPercent_min: 1,
    fighter_hitPenetrationPercent_max: 3,
    fighter_hitPenetrationPercent_incPercentByLevel: 10,
    fighter_evasionPercent_min: 15,
    fighter_evasionPercent_max: 20,
    fighter_evasionPercent_incPercentByLevel: 10,
    fighter_critChancePercent_min: 1,
    fighter_critChancePercent_max: 3,
    fighter_critChancePercent_incPercentByLevel: 10,
    fighter_critPowerPercent_min: 150,
    fighter_critPowerPercent_max: 175,
    fighter_rotationSpeedFactor: 1,
    fighter_jumpDelayInSec_min: 0.5,
    fighter_jumpDelayInSec_max: 1,
    fighter_jumpResetInSec_min: 0.5,
    fighter_jumpResetInSec_max: 1,
    fighter_jumpRadius: 1,
    fighter_suckRadius: 1,
    fighter_suckPowerInSec_min: 0.5,
    fighter_suckPowerInSec_max: 1,
    fighter_explosionDamage_min: 10,
    fighter_explosionDamage_max: 30,
    fighter_explosionDamage_incPercentByLevel: 10,
    fighter_explosionRadius: 1,

    // linkor

    linkor_hp: 30,
    linkor_hp_incPercentByLevel: 10,
    linkor_shield_min: 200,
    linkor_shield_max: 270,
    linkor_shield_incPercentByLevel: 10,
    linkor_attackPower_min: 20,
    linkor_attackPower_max: 30,
    linkor_attackPower_incPercentByLevel: 10,
    linkor_attackSpeedPersSec_min: 0.5,
    linkor_attackSpeedPersSec_max: 0.8,
    linkor_hitPenetrationPercent_min: 3,
    linkor_hitPenetrationPercent_max: 5,
    linkor_hitPenetrationPercent_incPercentByLevel: 10,
    linkor_evasionPercent_min: 3,
    linkor_evasionPercent_max: 5,
    linkor_evasionPercent_incPercentByLevel: 10,
    linkor_critChancePercent_min: 2,
    linkor_critChancePercent_max: 3,
    linkor_critChancePercent_incPercentByLevel: 10,
    linkor_critPowerPercent_min: 200,
    linkor_critPowerPercent_max: 250,
    linkor_rotationSpeedFactor: 0.7,
    linkor_jumpDelayInSec_min: 1,
    linkor_jumpDelayInSec_max: 1.5,
    linkor_jumpResetInSec_min: 1,
    linkor_jumpResetInSec_max: 1.5,
    linkor_jumpRadius: 1,
    linkor_suckRadius: 1,
    linkor_suckPowerInSec_min: 3,
    linkor_suckPowerInSec_max: 5,
    linkor_explosionDamage_min: 40,
    linkor_explosionDamage_max: 60,
    linkor_explosionDamage_incPercentByLevel: 10,
    linkor_explosionRadius: 3

}